### ISSUE TITLE
missing link

### ISSUE THREAD

**Issue by toyot-li** [leaf1170124460/Mask3D-SHIFT#6]
Hi @leaf1170124460 @suniique  https://github.com/suniique/SHIFT-3D-challenge/blob/challenge/annotations/SHIFT_challenge2023_multitask.zip is not valid now?

**Comment by leaf1170124460** [comment]
Hi, @zen-d.
Thanks for your feedback. We have updated the download link in README. You can also download this file from [here](https://drive.google.com/file/d/1lHLJmFO5xcV4wFq6rRgOKLWKDJei_hv4/view?usp=sharing).

**Comment by toyot-li** [comment]
@leaf1170124460 Hi, during testing with the command 
```bash
bash tools/dist_test.sh projects/configs/detr3d_r101_with_seg_depth_shift_minival_8bit.py 8 --checkpoint epoch_10.pth --format-only
```
It raises an error
```bash
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 2000/2000, 45.3 task/s, elapsed: 44s, ETA:     0sTraceback (most recent call last):                
  File "tools/test.py", line 252, in <module>                                                                         
    main()                                                                                                                                              
  File "tools/test.py", line 238, in main                                                                                               
    dataset.format_results(outputs, jsonfile_prefix=args.show_dir, **kwargs)         
  File "/home/user/Mask3D-SHIFT/projects/mmdet3d_plugin/datasets/shift/mmdet3d_dataset.py", line 468, in format_results                               
    "det_insseg_2d": self.seg_results2scalabel(results, jsonfile_prefix, **kwargs),                                   
  File "/home/user/Mask3D-SHIFT/projects/mmdet3d_plugin/datasets/shift/mmdet3d_dataset.py", line 359, in seg_results2scalabel         
    label = Label(                                                                                                
  File "/home/user/.conda/envs/shift/lib/python3.8/site-packages/scalabel/label/typing.py", line 91, in __init__     
    super().__init__(**data)                                                                                        
  File "/home/user/.conda/envs/shift/lib/python3.8/site-packages/pydantic/main.py", line 159, in __init__                             
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)           
pydantic_core._pydantic_core.ValidationError: 4 validation errors for Label                                            
box2d                                                                                                                           
  Field required [type=missing, input_value={'id': '0', 'category': '...R`0', size=(800, 1280))}, input_type=dict]                                       
    For further information visit https://errors.pydantic.dev/2.1/v/missing                                                     
box3d                                                                                                                  
  Field required [type=missing, input_value={'id': '0', 'category': '...R`0', size=(800, 1280))}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing                                               
poly2d                                                                                                                    
  Field required [type=missing, input_value={'id': '0', 'category': '...R`0', size=(800, 1280))}, input_type=dict]     
    For further information visit https://errors.pydantic.dev/2.1/v/missing                                           
graph                                                                                                                     
  Field required [type=missing, input_value={'id': '0', 'category': '...R`0', size=(800, 1280))}, input_type=dict]                      
    For further information visit https://errors.pydantic.dev/2.1/v/missing
```

**Comment by leaf1170124460** [comment]
Thanks for your feedback. We tested both the default config and 8bit config, but we didn't meet this error. 
The command in README also contains `--out` and `--show-dir`. You can try to add these two arguments and use the default config rather than 8bit config.

**Comment by toyot-li** [comment]
@leaf1170124460 Hello, thanks for your prompt reply. I have tried different configs and different arguments, but still stucked in this error. May I know your `scalabel` version?

**Comment by leaf1170124460** [comment]
We use scalabel==0.3.0, the same version as in README.
